name: "build and test feature branch"
on:
  push:
    branches:
      - feature/*
jobs:
  build-feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: pull and checkout from git repository
       
        run:
            echo "pulling and checking out from git repository"

      - name: setup java 21 
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'

      - name: build with maven
        run:
         mvnw clean install
         echo "build with maven"  
